### ISSUE TITLE
Making mimosa-bower work with polymerjs

### ISSUE THREAD

**Issue by bhavinkamani** [dbashford/mimosa-bower#40]
I am currently experimenting with [polymerjs](http://www.polymer-project.org/). All of the `polymerjs components` do not declare `main` in `bower.json`. Hence I have set `bower.copy.unknownMainFullCopy` to `true`. 

On `mimosa build`, js files are moved to `public/javascripts/vendor` and rest of the files are moved into `public/stylesheets/vendor`. Is there a way to keep all of the package files intact without these separations? I would prefer not to use `mainOverrides` as there are too many components for which override will have to be configured. Also is it possible to move all of them under a separate path without pre-processing them? In polymer, html files are typically imported using the new `html-import`. They internally refer to dependent javascript and css as a relative path. My `mimosa-config.coffee` file is as follows

```
exports.config = 
  modules: ["copy", "jshint", "csslint", "server", "require", "minify-js", "minify-css", "live-reload", "bower", "jade", "stylus", "coffeescript"]
  bower:
    copy:
      unknownMainFullCopy: true
```
