### ISSUE TITLE
Allow strategy to be at package level

### ISSUE THREAD

**Issue by dbashford** [dbashford/mimosa-bower#5]
From #4 

`strategy` should allow for the following possibilities:

```
strategy: "..."
```

This is the current setup.  Need to maintain not so much for its backwards compatibility but for its ease of use.

```
    strategy:
      "*": "..."
      package1: "..."
      package2: "..."
```

An object can be provided that allows for defining specific strategies.  `"*"` would cover any packages not defining a specific strategy.  If `"*"` is not defined then any package not listed would get the overall default strategy of `packageRoot`.
